spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=86400000
jwt.header=Authorization
jwt.token-prefix=Bearer

spring.jpa.hibernate.ddl-auto=validate

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE


admin.username=${ADMIN_USERNAME:admin}
admin.password=${ADMIN_PASSWORD}
admin.email=${ADMIN_EMAIL:admin@gmail.com}